"""chess_annotator

A small pipeline that turns a raw chess game (PGN) into natural-language,
move-by-move annotations, generated by a small language model (SLM) that is
conditioned on structured, engine-derived features rather than being asked
to "understand" the board itself.

Design principle: separate what is TRUE (deterministic, computed from the
chess engine and board state: eval swing, best move, material, move-quality
label) from what needs LANGUAGE (a fluent, human-readable explanation of
those facts). The SLM's only job is controlled natural-language generation
grounded in a structured record -- it never has to play or evaluate chess.
"""

from . import features, prompts, llm_backends, annotate  # noqa: F401
